# Generated by Django 3.0.1 on 2020-01-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad_personas', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('notas', models.TextField()),
            ],
        ),
    ]
