# Generated by Django 3.0.2 on 2020-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarios', '0002_auto_20200107_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='casa',
            field=models.IntegerField(),
        ),
    ]
