# Generated by Django 3.0.2 on 2020-01-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarios', '0005_auto_20200115_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
