# Generated by Django 3.0.2 on 2020-01-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarios', '0007_auto_20200115_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
