# Generated by Django 3.0.8 on 2020-10-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarios', '0008_auto_20200120_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='cantidad_personas',
            new_name='cantidad_adultos',
        ),
        migrations.AddField(
            model_name='reservas',
            name='cantidad_gratis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservas',
            name='cantidad_menores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservas',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Libre'), (1, 'Pendiente'), (2, 'Ocupado')], default=2),
        ),
    ]
