# Generated by Django 3.0.8 on 2020-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarios', '0011_reservas_tipo_adelanto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='deposito_inicial',
            field=models.IntegerField(default=0),
        ),
    ]
