# Generated by Django 3.1.2 on 2020-11-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarios', '0013_auto_20201030_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='deposito_inicial',
            new_name='deposito',
        ),
    ]
